[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake", "openssl"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python3.11 main.py"
